### ISSUE TITLE
Punctuation filter

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Multilingual-Parallel-Corpus#23]
Some parallel sentences like the abkhazian "Иашарыла умҩа қәҵоуп." and the russian "Кто ещё такой, как ты?" don't share the same punctuation marks. https://github.com/danielinux7/Multilingual-Parallel-Corpus/commit/65667b16cb4ac5c96c922cfb0b00e14f06d947d9 adds a hard punctuation filter to the join corpus script. The issue was initial described in https://github.com/danielinux7/Multilingual-Parallel-Corpus/issues/11
A more sensitive implementation should be described in the sprint planning.

**Comment by Bachstelze** [comment]
The sensitive implementation should also consider that different quote signs are valid.
Example from #36: ['Рауль Хаджимба: газета «Республика Абхазия» – один из самых читаемых и достоверных источников информации', 'Рауль Ҳаџьымба: агазеҭ “Республика Абхазия” – зегь реиҳа изыԥхьо, зегь реиҳа иҵабыргу аинформациатә хыҵхырҭақәа иреиуоуп\n']

**Comment by danielinux7** [comment]
I noticed their is an additional comma in this example, so even with the quotation sensitivy solution, the sentence will still be filtered out.
I think there should be different sensitivity levels for punctuation marks. Then I could test on these different levels and see how much it's acceptable.
So it's good to have this level of verbosity, in order to get high quality parallel corpuses, you could add different levels of sensitivity.

**Comment by Bachstelze** [comment]
The comma isn't included in the sentence signs.
I am still not sure which sensitive levels are helpful, but that is open to a sprint planning.
